# Generated by Django 2.1.4 on 2020-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataView', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
